const assetUrl = (path) => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`;

export const assetPacks = [
  {
    id: 'road-bits',
    name: 'Road Bits',
    url: assetUrl('/assets/road-bits.glb'),
    splitChildren: true,
    kind: 'road',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'store',
    name: 'Store',
    url: assetUrl('/assets/Store.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'small-building',
    name: 'Small Building',
    url: assetUrl('/assets/Small%20Building.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'low-building',
    name: 'Low Building',
    url: assetUrl('/assets/Low%20Building.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'large-building',
    name: 'Large Building',
    url: assetUrl('/assets/Large%20Building.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'building-red',
    name: 'Building Red',
    url: assetUrl('/assets/Building%20Red.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'wide-building',
    name: 'Wide Building',
    url: assetUrl('/assets/Wide%20Building.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'pizza-corner',
    name: 'Pizza Corner',
    url: assetUrl('/assets/Pizza%20Corner.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'skyscraper',
    name: 'Skyscraper',
    url: assetUrl('/assets/Skyscraper.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'skyscraper-2',
    name: 'Skyscraper 2',
    url: assetUrl('/assets/Skyscraper2.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'skyscraper-3',
    name: 'Skyscraper 3',
    url: assetUrl('/assets/Skyscraper3.glb'),
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'tree',
    name: 'Tree',
    url: assetUrl('/assets/misc/Tree.glb'),
    kind: 'foliage',
    scale: 1,
    rotationStep: 45,
  },
  {
    id: 'pine-trees',
    name: 'Pine Trees',
    url: assetUrl('/assets/misc/Pine%20Trees.glb'),
    splitChildren: true,
    kind: 'foliage',
    scale: 1,
    rotationStep: 45,
  },
  {
    id: 'streetlight',
    name: 'Streetlight',
    url: assetUrl('/assets/Streetlight.glb'),
    kind: 'streetlight',
    scale: 0.58,
    rotationStep: 90,
  },
  {
    id: 'car',
    name: 'Car',
    url: assetUrl('/assets/cars/Car.glb'),
    kind: 'car',
    scale: 0.0108,
    rotationStep: 90,
    showInPalette: false,
    trafficForwardAxis: 'z',
  },
  {
    id: 'red-car',
    name: 'Red Car',
    url: assetUrl('/assets/cars/Red%20Car.glb'),
    kind: 'car',
    scale: 0.52,
    rotationStep: 90,
    showInPalette: false,
    trafficForwardAxis: '-z',
  },
  {
    id: 'police-car',
    name: 'Police Car',
    url: assetUrl('/assets/cars/Police%20Car.glb'),
    kind: 'car',
    scale: 0.315,
    rotationStep: 90,
    showInPalette: false,
    trafficForwardAxis: 'z',
  },
  {
    id: 'fire-truck',
    name: 'Fire Truck',
    url: assetUrl('/assets/cars/Fire%20Truck.glb'),
    kind: 'car',
    scale: 1.9,
    rotationStep: 90,
    showInPalette: false,
    trafficForwardAxis: 'x',
  },
  {
    id: 'fire',
    name: 'Fire',
    url: assetUrl('/assets/misc/Fire.glb'),
    kind: 'effect',
    scale: 0.34,
    rotationStep: 45,
    showInPalette: false,
  },
  {
    id: 'animated-woman',
    name: 'Animated Woman',
    url: assetUrl('/assets/people/Animated%20Woman.glb'),
    kind: 'person',
    scale: 0.22,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'animated-woman-2',
    name: 'Animated Woman 2',
    url: assetUrl('/assets/people/Animated%20Woman%20%281%29.glb'),
    kind: 'person',
    scale: 0.076,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'hoodie-character',
    name: 'Hoodie Character',
    url: assetUrl('/assets/people/Hoodie%20Character.glb'),
    kind: 'person',
    scale: 0.22,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'man-in-long-sleeves',
    name: 'Man in Long Sleeves',
    url: assetUrl('/assets/people/Man%20in%20Long%20Sleeves.glb'),
    kind: 'person',
    scale: 0.082,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'man-in-suit',
    name: 'Man in Suit',
    url: assetUrl('/assets/people/Man%20in%20Suit.glb'),
    kind: 'person',
    scale: 0.082,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'worker',
    name: 'Worker',
    url: assetUrl('/assets/people/Worker.glb'),
    kind: 'person',
    scale: 0.216,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
];
