export const assetPacks = [
  {
    id: 'road-bits',
    name: 'Road Bits',
    url: '/assets/road-bits.glb',
    splitChildren: true,
    kind: 'road',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'store',
    name: 'Store',
    url: '/assets/Store.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'small-building',
    name: 'Small Building',
    url: '/assets/Small%20Building.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'low-building',
    name: 'Low Building',
    url: '/assets/Low%20Building.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'large-building',
    name: 'Large Building',
    url: '/assets/Large%20Building.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'building-red',
    name: 'Building Red',
    url: '/assets/Building%20Red.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'wide-building',
    name: 'Wide Building',
    url: '/assets/Wide%20Building.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'pizza-corner',
    name: 'Pizza Corner',
    url: '/assets/Pizza%20Corner.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'skyscraper',
    name: 'Skyscraper',
    url: '/assets/Skyscraper.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'skyscraper-2',
    name: 'Skyscraper 2',
    url: '/assets/Skyscraper2.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'skyscraper-3',
    name: 'Skyscraper 3',
    url: '/assets/Skyscraper3.glb',
    kind: 'building',
    scale: 1,
    rotationStep: 90,
  },
  {
    id: 'tree',
    name: 'Tree',
    url: '/assets/misc/Tree.glb',
    kind: 'foliage',
    scale: 1,
    rotationStep: 45,
  },
  {
    id: 'pine-trees',
    name: 'Pine Trees',
    url: '/assets/misc/Pine%20Trees.glb',
    splitChildren: true,
    kind: 'foliage',
    scale: 1,
    rotationStep: 45,
  },
  {
    id: 'car',
    name: 'Car',
    url: '/assets/cars/Car.glb',
    kind: 'car',
    scale: 0.0108,
    rotationStep: 90,
    showInPalette: false,
    trafficForwardAxis: 'z',
  },
  {
    id: 'red-car',
    name: 'Red Car',
    url: '/assets/cars/Red%20Car.glb',
    kind: 'car',
    scale: 0.52,
    rotationStep: 90,
    showInPalette: false,
    trafficForwardAxis: '-z',
  },
  {
    id: 'police-car',
    name: 'Police Car',
    url: '/assets/cars/Police%20Car.glb',
    kind: 'car',
    scale: 0.315,
    rotationStep: 90,
    showInPalette: false,
    trafficForwardAxis: 'z',
  },
  {
    id: 'animated-woman',
    name: 'Animated Woman',
    url: '/assets/people/Animated%20Woman.glb',
    kind: 'person',
    scale: 0.22,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'animated-woman-2',
    name: 'Animated Woman 2',
    url: '/assets/people/Animated%20Woman%20%281%29.glb',
    kind: 'person',
    scale: 0.076,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'hoodie-character',
    name: 'Hoodie Character',
    url: '/assets/people/Hoodie%20Character.glb',
    kind: 'person',
    scale: 0.22,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'man-in-long-sleeves',
    name: 'Man in Long Sleeves',
    url: '/assets/people/Man%20in%20Long%20Sleeves.glb',
    kind: 'person',
    scale: 0.082,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'man-in-suit',
    name: 'Man in Suit',
    url: '/assets/people/Man%20in%20Suit.glb',
    kind: 'person',
    scale: 0.082,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
  {
    id: 'worker',
    name: 'Worker',
    url: '/assets/people/Worker.glb',
    kind: 'person',
    scale: 0.216,
    rotationStep: 90,
    showInPalette: false,
    personForwardAxis: 'z',
  },
];
